// Generated by CoffeeScript 1.8.0
(function() {
  var app;

  app = angular.module("Grabba", ["ngStorage"]);

  app.controller("ListsController", function($scope, $localStorage, $sessionStorage) {
    $scope.$storage = $localStorage;
    if (!$scope.$storage.lists) {
      $scope.$storage.lists = [];
    }
    $scope.list = {};
    $scope.list.items = [];
    $scope.addList = function() {
      $scope.creatingList = 'false';
      $scope.list.createdAt = Date.now();
      $scope.$storage.lists.push($scope.list);
      return $scope.list = {};
    };
    $scope.removeAll = function() {
      return $scope.$storage.reset();
    };
    $scope.removeList = function(list) {
      var listPosition, lists;
      lists = $scope.$storage.lists;
      listPosition = lists.indexOf(list);
      lists.splice(listPosition, 1);
      return $scope.$storage.lists;
    };
    $scope.logList = function(list) {
      return console.log(list);
    };
    return $scope.viewList = function(list) {};
  });

  app.controller("ItemsController", function($scope) {
    $scope.item = {};
    return $scope.addItem = function(list) {
      var newItem;
      newItem = $scope.item;
      newItem.createdAt = Date.now();
      newItem.toPurchase = true;
      list.items.push(newItem);
      return $scope.item = {};
    };
  });

}).call(this);
